import 'package:nectar_store/Prodect.dart';

class AppData {
  static List<Product> allProducts = [
    Product(
      name: 'Red Apple',
      quantity: 50,
      price: 1.50,
      imagePath: 'assets/images/Apple.png',
      detiles: 'Fresh high-quality red apple - 1 kg',
      category: 'Fresh Fruits',
    ),
    Product(
      name: 'Pineapple',
      quantity: 20,
      price: 4.99,
      imagePath: 'assets/images/Fresh Pineapple Isolated.jpg',
      detiles: 'Fresh tropical pineapple - 1 piece',
      category: 'Fresh Fruits',
    ),
    Product(
      name: 'Coconut',
      quantity: 15,
      price: 3.50,
      imagePath: 'assets/images/gos-Hind.jpg',
      detiles: 'Fresh natural coconut - 1 piece',
      category: 'Fresh Fruits',
    ),
    Product(
      name: 'Green Grapes',
      quantity: 30,
      price: 2.50,
      imagePath: 'assets/images/grapes.jpg',
      detiles: 'Seedless green grapes - 1 kg',
      category: 'Fresh Fruits',
    ),
    Product(
      name: 'Kiwi',
      quantity: 40,
      price: 3.20,
      imagePath: 'assets/images/Kiwi.jpg',
      detiles: 'Fresh kiwi rich in vitamin C - 1 kg',
      category: 'Fresh Fruits',
    ),
    Product(
      name: 'Orange',
      quantity: 50,
      price: 1.50,
      imagePath: 'assets/images/orange.jpg',
      detiles: 'Fresh sweet oranges - 1 kg',
      category: 'Fresh Fruits',
    ),
    Product(
      name: 'Pomegranate',
      quantity: 25,
      price: 2.00,
      imagePath: 'assets/images/Romman.jpg',
      detiles: 'Sweet red pomegranate - 1 kg',
      category: 'Fresh Fruits',
    ),
    Product(
      name: 'Strawberry',
      quantity: 35,
      price: 2.99,
      imagePath: 'assets/images/strawberry.jpg',
      detiles: 'Fresh sweet strawberries - 1 box',
      category: 'Fresh Fruits',
    ),
    Product(
      name: 'Banana',
      quantity: 10,
      price: 1.00,
      imagePath: 'assets/images/banana.jpeg',
      detiles: 'Fresh banana',
      category: 'Fresh Fruits',
    ),

    Product(
      name: 'Broccoli',
      quantity: 15,
      price: 1.99,
      imagePath: 'assets/images/broklie.jpg',
      detiles: 'Fresh green broccoli - 1 piece',
      category: 'Vegetables',
    ),
    Product(
      name: 'Eggplant',
      quantity: 30,
      price: 1.10,
      imagePath: 'assets/images/btengan.jpg',
      detiles: 'Fresh local eggplant - 1 kg',
      category: 'Vegetables',
    ),
    Product(
      name: 'Carrots',
      quantity: 60,
      price: 1.20,
      imagePath: 'assets/images/carrots.jpg',
      detiles: 'Fresh local carrots - 1 kg',
      category: 'Vegetables',
    ),
    Product(
      name: 'Fresh Greens',
      quantity: 40,
      price: 0.50,
      imagePath: 'assets/images/grass.jpg',
      detiles: 'Fresh leafy greens - 1 bunch',
      category: 'Vegetables',
    ),
    Product(
      name: 'Cauliflower',
      quantity: 20,
      price: 1.50,
      imagePath: 'assets/images/karnbeet.jpg',
      detiles: 'Fresh cauliflower - 1 piece',
      category: 'Vegetables',
    ),
    Product(
      name: 'Lettuce',
      quantity: 30,
      price: 0.99,
      imagePath: 'assets/images/khas.jpg',
      detiles: 'Fresh green lettuce - 1 piece',
      category: 'Vegetables',
    ),
    Product(
      name: 'Onions',
      quantity: 70,
      price: 0.85,
      imagePath: 'assets/images/onion.jpg',
      detiles: 'Fresh red onions - 1 kg',
      category: 'Vegetables',
    ),
    Product(
      name: 'Potatoes',
      quantity: 80,
      price: 1.10,
      imagePath: 'assets/images/potatoes.jpg',
      detiles: 'Fresh potatoes for frying and cooking - 1 kg',
      category: 'Vegetables',
    ),
    Product(
      name: 'Red Pepper',
      quantity: 30,
      price: 2.00,
      imagePath: 'assets/images/red-felfel.png',
      detiles: 'Fresh red bell pepper - 1 kg',
      category: 'Vegetables',
    ),
    Product(
      name: 'Tomatoes',
      quantity: 100,
      price: 0.99,
      imagePath: 'assets/images/tomatoes.jpg',
      detiles: 'Fresh red tomatoes for cooking and salads - 1 kg',
      category: 'Vegetables',
    ),
    Product(
      name: 'Garlic',
      quantity: 40,
      price: 3.00,
      imagePath: 'assets/images/toom.jpg',
      detiles: 'Fresh white garlic - 1 kg',
      category: 'Vegetables',
    ),

    Product(
      name: 'Beef Cuts',
      quantity: 10,
      price: 15.99,
      imagePath: 'assets/images/beef.jpg',
      detiles: 'Fresh pure beef cuts - 1 kg',
      category: 'Meat & Fish',
    ),
    Product(
      name: 'Whole Chicken',
      quantity: 25,
      price: 6.50,
      imagePath: 'assets/images/Chicken-2.png',
      detiles: 'Fresh whole chicken - 1200g',
      category: 'Meat & Fish',
    ),
    Product(
      name: 'Chicken Meat',
      quantity: 20,
      price: 7.50,
      imagePath: 'assets/images/chicken-meat4.jpg',
      detiles: 'Fresh chicken cuts - 1 kg',
      category: 'Meat & Fish',
    ),
    Product(
      name: 'Fish Fillet',
      quantity: 12,
      price: 9.99,
      imagePath: 'assets/images/fish3.jpg',
      detiles: 'White fish fillet without bones - 1 kg',
      category: 'Meat & Fish',
    ),
    Product(
      name: 'Fresh Fish',
      quantity: 15,
      price: 8.50,
      imagePath: 'assets/images/fish8.jpg',
      detiles: 'Freshly caught fish - 1 kg',
      category: 'Meat & Fish',
    ),
    Product(
      name: 'Minced Meat',
      quantity: 15,
      price: 14.50,
      imagePath: 'assets/images/la7ma-mafrooma.jpg',
      detiles: 'Low-fat minced beef - 1 kg',
      category: 'Meat & Fish',
    ),
    Product(
      name: 'Fresh Meat',
      quantity: 10,
      price: 16.00,
      imagePath: 'assets/images/Meat.jpg',
      detiles: 'Fresh meat cuts - 1 kg',
      category: 'Meat & Fish',
    ),
    Product(
      name: 'Premium Meat',
      quantity: 12,
      price: 18.00,
      imagePath: 'assets/images/Meat(2).png',
      detiles: 'Premium quality meat cuts - 1 kg',
      category: 'Meat & Fish',
    ),
    Product(
      name: 'Meat Chops',
      quantity: 15,
      price: 15.50,
      imagePath: 'assets/images/meat5.jpg',
      detiles: 'Fresh meat chops - 1 kg',
      category: 'Meat & Fish',
    ),

    Product(
      name: 'White Toast',
      quantity: 30,
      price: 1.50,
      imagePath: 'assets/images/Bread.jpg',
      detiles: 'Fresh white toast bread - 1 pack',
      category: 'Bakery & Snacks',
    ),
    Product(
      name: 'Fresh Bread',
      quantity: 20,
      price: 1.20,
      imagePath: 'assets/images/bread3.jpg',
      detiles: 'Fresh bakery bread - 1 pack',
      category: 'Bakery & Snacks',
    ),
    Product(
      name: 'Chocolate Eclair',
      quantity: 15,
      price: 3.50,
      imagePath: 'assets/images/Chocolate Eclairs.jpg',
      detiles: 'Eclair stuffed and covered with chocolate - 2 pieces',
      category: 'Bakery & Snacks',
    ),
    Product(
      name: 'Croissant',
      quantity: 40,
      price: 2.00,
      imagePath: 'assets/images/croassons.jpg',
      detiles: 'Plain butter croissant - 3 pieces',
      category: 'Bakery & Snacks',
    ),
    Product(
      name: "Thorin's Bread",
      quantity: 15,
      price: 2.50,
      imagePath: "assets/images/Thorin's bread.jpg",
      detiles: "Special Thorin's bakery bread",
      category: 'Bakery & Snacks',
    ),

    Product(
      name: 'Ahmed Tea',
      quantity: 50,
      price: 2.50,
      imagePath: 'assets/images/Ahmedtee.jpeg',
      detiles: 'Ahmed Tea Black Tea - 1 pack',
      category: 'Drinks',
    ),
    Product(
      name: 'Apple Juice',
      quantity: 40,
      price: 2.50,
      imagePath: 'assets/images/Apple-juice.png',
      detiles: '100% natural apple juice - 1 Liter',
      category: 'Drinks',
    ),
    Product(
      name: 'Coca Cola Can',
      quantity: 100,
      price: 0.99,
      imagePath: 'assets/images/coke.png',
      detiles: 'Coca Cola carbonated drink - 330ml',
      category: 'Drinks',
    ),
    Product(
      name: 'Monster Energy',
      quantity: 40,
      price: 3.50,
      imagePath: 'assets/images/Monster.jpg',
      detiles: 'Monster energy drink - 500ml',
      category: 'Drinks',
    ),
    Product(
      name: 'Nescafe Black',
      quantity: 25,
      price: 5.99,
      imagePath: 'assets/images/nescafe-black.jpg',
      detiles: 'Nescafe classic black coffee - 200g',
      category: 'Packaged Goods',
    ),
    Product(
      name: 'Monster Normal',
      quantity: 40,
      price: 3.50,
      imagePath: 'assets/images/normalMonster.jpg',
      detiles: 'Monster energy drink original - 500ml',
      category: 'Drinks',
    ),
    Product(
      name: 'Pepsi Can',
      quantity: 100,
      price: 0.99,
      imagePath: 'assets/images/Pepsi.png',
      detiles: 'Pepsi carbonated drink - 330ml',
      category: 'Drinks',
    ),
    Product(
      name: 'Pink Red Bull',
      quantity: 30,
      price: 2.99,
      imagePath: 'assets/images/pink-redBull.jpg',
      detiles: 'Red Bull energy drink pink edition - 250ml',
      category: 'Drinks',
    ),
    Product(
      name: 'Red Bull',
      quantity: 50,
      price: 2.99,
      imagePath: 'assets/images/red-bull.jpg',
      detiles: 'Red Bull energy drink original - 250ml',
      category: 'Drinks',
    ),
    Product(
      name: 'Sprite Can',
      quantity: 90,
      price: 0.99,
      imagePath: 'assets/images/Sprite.png',
      detiles: 'Sprite lemon carbonated drink - 330ml',
      category: 'Drinks',
    ),
    Product(
      name: 'Sting Energy',
      quantity: 40,
      price: 1.50,
      imagePath: 'assets/images/Sting.jpg',
      detiles: 'Sting energy drink - 330ml',
      category: 'Drinks',
    ),
    Product(
      name: 'Tang Juice',
      quantity: 25,
      price: 3.50,
      imagePath: 'assets/images/tang-juice.jpg',
      detiles: 'Tang orange instant drink powder',
      category: 'Packaged Goods',
    ),
    Product(
      name: 'White Monster',
      quantity: 40,
      price: 3.50,
      imagePath: 'assets/images/white-monster.jpg',
      detiles: 'Monster energy drink zero sugar - 500ml',
      category: 'Drinks',
    ),

    Product(
      name: 'Fresh Milk',
      quantity: 30,
      price: 2.20,
      imagePath: 'assets/images/milk2.jpg',
      detiles: 'Full cream fresh milk - 1 Liter',
      category: 'Packaged Goods',
    ),

    Product(
      name: 'Cheddar Cheese',
      quantity: 25,
      price: 4.50,
      imagePath:
          'assets/images/Cheese Packaging Design #cheese #cheesepackaging….jpg',
      detiles: 'Original cheddar cheese slices - 200g',
      category: 'Packaged Goods',
    ),
    Product(
      name: 'Nido Milk',
      quantity: 35,
      price: 12.50,
      imagePath: 'assets/images/NidoMilk .jpg',
      detiles: 'Nido full cream milk powder - 900g',
      category: 'Packaged Goods',
    ),
    Product(
      name: 'Noodles',
      quantity: 80,
      price: 1.20,
      imagePath: 'assets/images/Noodles.png',
      detiles: 'Instant noodles chicken flavor',
      category: 'Packaged Goods',
    ),
    Product(
      name: 'Nutella',
      quantity: 20,
      price: 8.99,
      imagePath: 'assets/images/nutella.jpg',
      detiles: 'Nutella hazelnut chocolate spread - 400g',
      category: 'Packaged Goods',
    ),
    Product(
      name: 'Oreo',
      quantity: 60,
      price: 1.50,
      imagePath: 'assets/images/Oreo.jpg',
      detiles: 'Oreo chocolate sandwich cookies - 1 pack',
      category: 'Bakery & Snacks',
    ),
    Product(
      name: 'Pillows Cereal',
      quantity: 20,
      price: 4.50,
      imagePath: 'assets/images/pillows.jpg',
      detiles: 'Chocolate filled pillows cereal - 1 box',
      category: 'Bakery & Snacks',
    ),
    Product(
      name: 'Pringles',
      quantity: 40,
      price: 2.99,
      imagePath: 'assets/images/pringles2.jpg',
      detiles: 'Pringles potato chips original - 1 can',
      category: 'Packaged Goods',
    ),
    // Product(
    //   name: 'Rajma Recipe',
    //   quantity: 15,
    //   price: 3.50,
    //   imagePath: 'assets/images/Quick and Easy Rajma Recipe (Red Kidn...',
    //   detiles: 'Quick and Easy Rajma Recipe Pack',
    //   category: 'Packaged Goods',
    // ),
    Product(
      name: 'Rani Ghee',
      quantity: 10,
      price: 15.00,
      imagePath: 'assets/images/Rani Pure Natural Ghee from Grass Fed Cows (Clarified Butter) 1lb (16oz) ~ Glass Jar _ Paleo Friendly _ Keto Friendly _ Gluten Free #40649 _ DesiClik_com, USA.jpg',
      detiles: 'Rani Pure Natural Ghee from Grass Fed Cows',
      category: 'Meat & Fish',
    ),
    Product(
      name: 'Doritos',
      quantity: 60,
      price: 1.99,
      imagePath: 'assets/images/red-doritos.jpg',
      detiles: 'Doritos nacho cheese flavor - Family size',
      category: 'Bakery & Snacks',
    ),
    Product(
      name: 'Skittles',
      quantity: 40,
      price: 1.20,
      imagePath: 'assets/images/skittles.jpg',
      detiles: 'Skittles fruit flavored candies - 1 pack',
      category: 'Bakery & Snacks',
    ),
    Product(
      name: 'Snickers',
      quantity: 50,
      price: 1.50,
      imagePath: 'assets/images/Snikers.jpg',
      detiles: 'Snickers chocolate bar with peanuts',
      category: 'Bakery & Snacks',
    ),
  ];
}
